#!/bin/bash
# `./dokrun <args>`
# docker run wrapper that maps ENV to local paths

source config.sh # provides WEIGHTS_ROOT, DATA_ROOT, WEIGHTS_HOME, DATA_HOME

# optarg -h <local_path:container_path> # LOCAL CACHES to store torch_hub, huggingface_hub and dnnlib caches
# cache expand ./config.sh variables to both shared volumes and PATH in ./dockerrun and ./dockerglrun
DCACHE="${WEIGHTS_ROOT}:${WEIGHTS_HOME}"

# optarg -d  <local_path:container_path> # LOCAL DATA folder
DDATA="${DATA_ROOT}:${DATA_HOME}"
# DATA_HOME is added to path

# image infos
# optarg -i <imagename> # change to run anoter image
DIMAGE=""    # optarg -i <image_name>
DNAME=""     # optarg -n <container_name> if empty uses the last bit of the image name

# user and setup infos
DUSER="1000" # optarg -u <valid user id>
DGPU=0       # optarg -g <valid gpus>
DCPU="0-10"  # optarg -c <valid cpu range>
DSHM=10g     # optarg -m <shared memory> # increased from default
DX11=false

while getopts u:n:g:c:h:d:v:m:i:x option; do case ${option} in
i) DIMAGE=${OPTARG};;
u) DUSER=${OPTARG};;
n) DNAME=${OPTARG};;
g) DGPU=${OPTARG};;
c) DCPU=${OPTARG};;
h) DCACHE=${OPTARG};;
d) DDATA=${OPTARG};;
m) DSHM=${OPTARG};; # shared memory 10g default
x) DX11=true;; # run with X11 Display
esac; done

if [ -z "$DNAME" ]; then
    IFS="_" read -ra elements <<< "$DIMAGE"
    DNAME="${elements[-1]}"
fi

echo "${0} expands to:"
if docker images --format '{{.Repository}}:{{.Tag}}' | grep -q "^$DIMAGE"; then
    if [ "${DX11}" = true ]; then
        $( dirname $0 )/dockerglrun --user $DUSER --name $DNAME --gpus device=$DGPU --cpuset-cpus=$DCPU --shm-size $DSHM --cache $DCACHE -v $DDATA -e DATA_HOME=$DATA_HOME --network=host -it --rm $DIMAGE
    else
        $( dirname $0 )/dockerrun --user $DUSER --name $DNAME --gpus device=$DGPU --cpuset-cpus=$DCPU --shm-size $DSHM --cache $DCACHE -v $DDATA -e DATA_HOME=$DATA_HOME --network=host -it --rm $DIMAGE
    fi
else
    echo ERROR: docker image $DIMAGE not found, use one of ...
    docker images --format '{{.Repository}}:{{.Tag}}'
fi
