#!/bin/bash
# docker run with local dev options & shortcut to personal setups

# local paths infors
# optarg -h <local_path:container_path> # LOCAL CACHES to store torch_hub, huggingface_hub and dnnlib caches
DCACHE="/mnt/Data/weights:/home/weights"
# optarg -d  <local_path:container_path> # LOCAL DATA folder
DDATA="/mnt/Data/data:/home/data"

# image infos
# optarg -i <imagename> # change to run anoter image
DIMAGE="xvdp/cuda1180-ubuntu2204_ssh_mamba_torch_lang"
DNAME="lang" # optarg -n <containername>

# user and setup infos
DUSER="1000" # optarg -u <valid user id>
DGPU=0       # optarg -g <valid gpus>
DCPU="0-10"  # optarg -c <valid cpu range>
DSHM=10g     # optarg -m <shared memory> # increased from default 

while getopts u:n:g:c:h:d:v:m:i: option; do case ${option} in
i) DIMAGE=${OPTARG};;
u) DUSER=${OPTARG};;
n) DNAME=${OPTARG};;
g) DGPU=${OPTARG};;
c) DCPU=${OPTARG};;
h) DCACHE=${OPTARG};;
d) DDATA=${OPTARG};;
m) DSHM=${OPTARG};; # shared memory 10g default
esac; done

./dockerrun --user $DUSER --name $DNAME --gpus device=$DGPU --cpuset-cpus=$DCPU --shm-size $DSHM --cache $DCACHE -v $DDATA --network=host -it --rm $DIMAGE
