build:
  maintainer: "xvdp"
  user: 1001
  username: "z"
  images:
    cuda1280-cudnn-ubuntu2404_ssh:
      name: "ssh"
      baseimage: "nvidia/cuda:12.8.1-cudnn-devel-ubuntu24.04"
      auth_root: "~/.ssh"
    cuda1280-cudnn-ubuntu2404_ssh_mamba:
      name: "mamba"
      baseimage: "xvdp/cuda1280-cudnn-ubuntu2404_ssh"
    ubuntu22-04_cuda12-4_torch2-4:
      os: "ubuntu22.04"
      cuda: "12.4.1"
      torch: "2.5.1"
      base: "nvidia/cuda:12.4.1-cudnn-devel-ubuntu22.04"
      torch_install_cmd: "conda install pytorch==2.5.1 torchvision==0.20.1 torchaudio==2.5.1 pytorch-cuda=12.4 -c pytorch -c nvidia"
    ubuntu22-04_cuda12-4_torch2-4:
      os: "ubuntu22.04"
      cuda: "12.4.1"
      torch: "2.4.1"
      base: "nvidia/cuda:12.4.1-cudnn-devel-ubuntu22.04"
      torch_install_cmd: "conda install pytorch==2.4.1 torchvision==0.19.1 torchaudio==2.4.1 pytorch-cuda=12.4 -c pytorch -c nvidia"
    ubuntu24-04_cuda12-6_torch2-6:
      os: "ubuntu24.04"
      cuda: "12.6.3"
      base: "nvidia/cuda:12.6.3-cudnn-devel-ubuntu24.04"
      torch_install_cmd: "pip3 install torch torchvision torchaudio --index-url https://download.pytorch.org/whl/cu126" 
    ubuntu24-04_cuda12-8_torch2-8:
      os: "ubuntu24.04"
      cuda: "12.8.0"
      base: "nvidia/cuda:12.8.1-cudnn-devel-ubuntu24.04"
      torch_install_cmd: "pip3 install --pre torch torchvision torchaudio --index-url https://download.pytorch.org/whl/nightly/cu128"
run:
  environments:
    -e "XDG_CACHE_HOME=/home/weights"
    -e "TORCH_HOME=/home/weights/torch"
    -e "TORCH_EXTENSIONS_DIR=/home/weights/torch_extensions"
    -e "DNNLIB_CACHE_DIR=/home/weights/dnnlib"
    -e "HUGGINGFACE_HOME=/home/weights/huggingface"
    -e "HF_TOKEN"=$(cat /home/weights/huggingface/HF_TOKEN)
    -e "PROJECT=/home/DeepSeek/DeepSeek-V3"
    -e "DATA=/home/weights/DeepSeek-V3"
  images:
    deepseek:
      image: 'xvdp/cuda1241-cudnn-ubuntu2204_ssh_mamba_torch241_deepseek'
      user: 1001
      gpus: 1
      volumes:
        -v "/home/z/work24/gits/Language/DeepSeek:/home/DeepSeek"
        -v "/home/weights:/home/weights"
      wipvolumes:
        -v "/home/z/work24/gits/Language/DeepSeek/.python_history:/home/z/.python_history"




  
